import type { Scene } from '@/engine/types';
import {
  scene, n, d, sys, bg, ch, hide, clearCh, cg, closeCg, bgm, se, fx, wait,
  flag, p, choice, opt, jump, branch, chapter, breakFrame, ending,
  F, NF, AND, GTE, LTE, META,
} from '../dsl';

/**
 * 【第十三夜（TRUE）】12月25日「継ぎ足された夜」／終夜 12月26日
 *
 * 開放条件：F20 SEAM_STITCH（別周回でF14〜F19を3種以上）＋ OBS≧300。
 * これは全ルートの第十二夜末から分岐して入る、六人全員が揃う十三夜である。
 *
 * ここに余計な説明を足さないこと。最終行は必ずネオ。
 */

/** 各ルートの第十二夜末から呼ぶ共通ゲート。条件を満たさなければルート固有の十三夜へ戻す。 */
export const trueRoute: Scene[] = [
  scene('t13_gate',
    branch(
      [
        {
          cond: AND(F('SEAM_STITCH'), GTE('OBS', 300)),
          to: 't13_open',
        },
      ],
      't13_route_fallback',
    ),
  ),

  /** 条件未達なら、ルート固有の十三夜へ返す。 */
  scene('t13_route_fallback',
    branch(
      [
        { cond: { route: 'lenny' }, to: 'r_lenny_13' },
        { cond: { route: 'hugh' }, to: 'r_hugh_13' },
        { cond: { route: 'jinpachi' }, to: 'r_jin_13' },
        { cond: { route: 'muni' }, to: 'r_muni_13' },
        { cond: { route: 'geru' }, to: 'r_geru_13' },
        { cond: { route: 'neo' }, to: 'r_neo_13' },
      ],
      'ne1_open',
    ),
  ),

  /* ================= 第十三夜（TRUE） ================= */
  scene('t13_open',
    bg('black'),
    bgm(null),
    chapter(13, 'つぎたされたよる', '12月25日', 'omniscient', 'だれかが みている'),
    bg('slope_night', 'slowfade'),
    fx('snow-on'),
    n('十二月二十五日。'),
    n('カレンダーには、印刷の薄い数字だけがある。'),
    n('この日は、宵ノ辻の誰の予定表にも書かれていない。'),
    n('この日に生まれた者はなく、この日に死んだ者もない。'),
    n('毎年、十二月は二十四日の次に二十六日が来る。'),
    n('——ただし、七年に一度だけ、間に一晩、差し込まれる。'),
    n('継ぎ足された夜。'),
    n('その夜は、坂の上から始まった。'),
    se('streetlight_off'),
    cg('CG-41'),
    n('二十三時五十九分。'),
    n('坂のいちばん上の街灯が、消えた。'),
    n('次の一本が消えた。'),
    n('その次が消えた。'),
    n('一本ずつ。上から下へ。等間隔で。'),
    n('十三日の夜と、同じ順番で。'),
    n('そして、最後の一本が消えたとき、'),
    n('消えた光の下が、'),
    n('——開いた。'),
    closeCg(),
    jump('t13_six'),
  ),

  scene('t13_six',
    bg('boundary'),
    bgm('finale'),
    clearCh(),
    ch('LEN', 'awake', 'far-left'),
    ch('MUN', 'normal', 'left'),
    ch('HYU', 'eye', 'center'),
    ch('JIN', 'normal', 'right'),
    ch('GER', 'quiet', 'far-right'),
    n('六人が、そこにいた。'),
    n('誰も呼んでいない。誰も約束していない。'),
    n('それでも全員が、同じ夜に、同じ場所へ来ていた。'),
    n('境界の入口は、坂の下の街灯の、光があったはずの場所に、'),
    n('ちょうど人ひとりぶんの高さで、縦に裂けていた。'),
    n('裂け目の向こうは、青い。'),
    n('水の底の色をしていた。'),
    ch('NEO', 'resolve', 'right'),
    d('NEO', '……全員来たか。'),
    d('JIN', '来るに決まってんだろ。'),
    d('NEO', '愚かだ。'),
    d('JIN', 'お前もいるじゃねぇか。'),
    d('NEO', '——'),
    d('NEO', '……黙れ。'),
    jump('t13_deadlock'),
  ),

  scene('t13_deadlock',
    n('そして、この夜、決着はつかなかった。'),
    n('つかなかったのは、戦いに負けたからではない。'),
    n('勝ち方が、どれも、同じ形をしていたからだ。'),
    d('GER', '——錨は、分担できる。'),
    d('GER', '七人で分ければ、ムニは五歳のまま生きられる。'),
    d('GER', 'だが、七人全員が、毎晩、夢を町に貸すことになる。'),
    d('HYU', 'わたくしは、忘れ続けます。'),
    d('HYU', 'その術式を組めば組むほど、わたくしの中の線は焼き切れる。'),
    d('GER', '私は、自分の名を失う。'),
    d('GER', '名簿を返却台帳に書き換えれば、書いた者の名だけが返せない。'),
    d('NEO', '私は、故郷を失う。'),
    d('NEO', '残骸を斬れば、私の国は、私の手で終わる。'),
    d('JIN', '俺は、妹を忘れる。'),
    d('JIN', '名前を返すには、俺の中から抜くしかねぇ。'),
    d('MUN', 'ムニは、レニィの はんぶんを かえさなきゃ。'),
    d('LEN', '僕は、'),
    d('LEN', '……僕は、なにを?'),
    n('全員が、黙った。'),
    n('レニィだけが、何も失わない。'),
    n('レニィだけが、失うものを、もう七年前に、失い終えていた。'),
    jump('t13_lenny_line'),
  ),

  scene('t13_lenny_line',
    bgm('boundary'),
    clearCh(),
    ch('LEN', 'awake', 'center'),
    n('レニィが、裂け目のほうを見た。'),
    n('見て、それから、'),
    n('裂け目ではないところを、見た。'),
    n('誰もいない場所を。'),
    n('雪が、そこだけ、避けて落ちているように見える場所を。'),
    d('LEN', '……ねぇ。'),
    d('LEN', 'ずっと、だれかが見てるよね。', { slow: true }),
    n('雪の音が、止まった。'),
    d('JIN', '……レニィ?'),
    d('LEN', 'ずっとだよ。'),
    d('LEN', 'こたつで寝てたときも、公園でひかったときも、'),
    d('LEN', 'ムニが手紙おいてったときも、'),
    d('LEN', '——ずっと、そこから、見てた。'),
    d('HYU', 'レニィ。どこを見ているのです。'),
    d('LEN', 'ヒュウ。'),
    d('LEN', 'めを、あけて。'),
    d('LEN', 'さいごに、いっかいだけ。'),
    jump('t13_eye'),
  ),

  scene('t13_eye',
    n('ヒュウは、前髪に手をかけた。'),
    n('この目を開けば、また一本、線が焼き切れる。'),
    n('残りが何本あるのか、本人にも分からない。'),
    d('HYU', '……承知しました。'),
    d('HYU', 'ただし、条件がひとつ。'),
    d('JIN', 'なんだよ。'),
    d('HYU', '——わたくしが忘れたら、'),
    d('HYU', '教えてください。何度でも。'),
    d('JIN', '……ああ。'),
    d('JIN', '何度でも。'),
    se('heartbeat'),
    fx('dark-on'),
    cg('CG-08'),
    n('左の目が、開いた。'),
    n('赤い虹彩に、世界の縫い目が全部、映った。'),
    n('境界の裂け目。'),
    n('町の輪郭。'),
    n('六人の、それぞれの縫い目。'),
    n('そして、'),
    closeCg(),
    fx('flash', 400),
    jump('t13_observer'),
  ),

  scene('t13_observer',
    bg('boundary_deep'),
    bgm(null),
    clearCh(),
    cg('CG-44'),
    n('眠るレニィの上に、'),
    n('——重なっているものが、あった。'),
    n('輪郭がない。'),
    n('色もない。'),
    n('形を持たないのに、そこに「ある」と分かる。'),
    n('それは、レニィの体から少しだけ浮いて、'),
    n('ずっと、この町を見ていた。'),
    n('七年間。'),
    n('十二月十三日から、二十五日までを。'),
    n('何度も。'),
    n('何度も。'),
    closeCg(),
    d('HYU', '……見えました。'),
    d('JIN', '何が。'),
    d('HYU', '——観測者です。'),
    flag('TRUE_SEEN'),
    p({ OBS: 30 }),
    jump('t13_truth'),
  ),

  scene('t13_truth',
    bg('boundary'),
    bgm('finale'),
    clearCh(),
    ch('GER', 'broken', 'right'),
    ch('LEN', 'awake', 'left'),
    d('GER', '……そうか。'),
    d('GER', 'そういうことだったのか。'),
    d('JIN', '分かるように言え!'),
    d('GER', 'レニィが眠り続けているのは、錨だからではない。'),
    d('GER', '——眠っているから、錨でいられるのだ。'),
    d('GER', 'この子は、七年前に斬られたとき、'),
    d('GER', '眠る半分と、起きる半分に分かれた。'),
    d('GER', 'それは、知っていた。'),
    d('GER', 'だが、もうひとつ、分かれていた。'),
    d('GER', '——「見る力」だ。'),
    d('GER', 'この子は、自分の見る力を、体の外に置いている。'),
    d('GER', '外に置いた見る力が、この町を、ずっと見ている。'),
    d('GER', '見られているから、この町は、まだ在る。'),
    d('GER', '見られなくなれば、'),
    d('GER', '——町は、裏返る。'),
    jump('t13_meta'),
  ),

  scene('t13_meta',
    clearCh(),
    ch('LEN', 'awake', 'center'),
    d('LEN', 'ねぇ。'),
    d('LEN', '僕、なんども おなじ十二月を見てる気がするんだ。'),
    d('LEN', '十三日に灯が消えて、'),
    d('LEN', '十四日に鍋をして、'),
    d('LEN', '十七日にムニが五歳になって、'),
    d('LEN', '……なんども。'),
    d('MUN', 'ムニも。'),
    d('MUN', 'ムニ、ろうそくを けしたこと、いっぱいあるきがする。'),
    d('MUN', 'ごほんを、なんども。'),
    d('JIN', '……俺もだ。'),
    d('JIN', 'この坂、初めて上る気がしねぇ。'),
    d('HYU', 'わたくしは、覚えていません。'),
    d('HYU', 'ですが——覚えていないことを、何度も繰り返している気は、しております。'),
    n('レニィが、また、誰もいない場所を見た。'),
    d('LEN', 'ねぇ。'),
    d('LEN', 'きみは、なんかいめ?', { slow: true }),
    n('——'),
    n('その問いに、答えられる者は、'),
    n('この夜、坂の上には、いなかった。'),
    p({ OBS: 20 }),
    jump('t13_final_choice'),
  ),

  scene('t13_final_choice',
    bgm('boundary'),
    n('ゲルが、静かに言った。'),
    d('GER', '……方法は、ある。'),
    d('GER', '見る力を、体に戻せばいい。'),
    d('GER', 'そうすればレニィは本当に目覚める。錨は要らなくなる。'),
    d('GER', '誰も、何も失わない。'),
    d('JIN', 'じゃあ、それでいいじゃねぇか!'),
    d('GER', '——ひとつだけ、失う。'),
    d('HYU', '……ああ。'),
    d('HYU', '見る力が体に戻れば、'),
    d('HYU', '外で見ていた「それ」は、'),
    d('HYU', '——消えます。'),
    n('全員が、'),
    n('誰もいない場所を、'),
    n('見た。'),
    n('雪が、そこだけ、避けて落ちている場所を。'),
    n('六人が、'),
    n('こちらを、見ていた。'),
    breakFrame(true),
    choice('——どうする?',
      opt('見続ける', 'be07_from_true', {
        affection: { OBS: 10 },
      }),
      opt('見るのをやめる', 't13_true_end', {
        setFlags: ['OBSERVER'],
        enableIf: AND(F('SEAM_STITCH'), GTE('OBS', 300)),
        lockedNote: '（まだ、そこまで濃くない）',
      }),
    ),
  ),

  /* ================= TRUE END ================= */
  scene('t13_true_end',
    bg('boundary'),
    bgm(null),
    breakFrame(true),
    clearCh(),
    n('——決めた。'),
    n('決めた、ということが、'),
    n('六人には、伝わったらしい。'),
    n('ヒュウが、目を閉じた。'),
    n('ゲルが、名簿を閉じた。'),
    n('ジンパチが、手帳をポケットにしまった。'),
    n('ネオが、剣を鞘に収めた。'),
    n('全員が、こちらを向いた。'),
    n('この物語で、初めて。'),
    jump('t13_farewell'),
  ),

  scene('t13_farewell',
    bgm('finale'),
    clearCh(),
    ch('MUN', 'smile', 'center'),
    d('MUN', '……ばいばい、じゃなくて、'),
    d('MUN', 'おやすみ、だよね。', { slow: true }),
    hide('MUN'),
    ch('JIN', 'laugh', 'center'),
    d('JIN', '見ててくれてサンキューな。'),
    d('JIN', 'あとは自分たちでやる。', { slow: true }),
    hide('JIN'),
    ch('GER', 'quiet', 'center'),
    d('GER', '私はお前の名前を知らない。'),
    d('GER', '……だが、名簿に一行、空けておく。', { slow: true }),
    hide('GER'),
    ch('HYU', 'smile', 'center'),
    d('HYU', 'わたくしは忘れます。'),
    d('HYU', 'ですが、忘れることを、覚えておきます。', { slow: true }),
    hide('HYU'),
    ch('LEN', 'smile', 'center'),
    d('LEN', '僕、ちゃんと起きるからね。'),
    d('LEN', '……だから、もう寝ていいよぉ。', { slow: true }),
    hide('LEN'),
    jump('t13_neo_last'),
  ),

  scene('t13_neo_last',
    bg('slope_night'),
    clearCh(),
    ch('NEO', 'resolve', 'center'),
    n('最後に、金色の男が、一歩前に出た。'),
    n('この男は、ずっと、誰にも記録されないことを恐れていた。'),
    n('その男が、記録する側に向かって、口を開いた。'),
    d('NEO', '——行け。'),
    d('NEO', '貴様の朝は、こちらにはない。', { slow: true }),
    jump('t13_black'),
  ),

  scene('t13_black',
    bgm(null),
    clearCh(),
    breakFrame(false),
    bg('black', 'slowfade'),
    wait(2600),
    n('　'),
    wait(1800),
    n('　'),
    se('streetlight_on'),
    fx('flash', 1200),
    wait(1200),
    jump('t13_dawn'),
  ),

  scene('t13_dawn',
    bg('slope_morning', 'slowfade'),
    bgm('morning'),
    cg('CG-54'),
    n('　'),
    n('誰もいない坂を、朝日が上っていく。'),
    n('街灯は、一本残らず消えている。'),
    n('もう、灯る必要が、ないからだ。'),
    closeCg(),
    ending('TE-01'),
  ),

  /* ================= BE-07（見続ける） ================= */
  scene('be07_from_true',
    bg('boundary'),
    bgm(null),
    breakFrame(true),
    clearCh(),
    n('——見続けることにした。'),
    n('見ていたかった。'),
    n('この六人を、まだ、見ていたかった。'),
    n('それは、たぶん、いちばん優しい選択だった。'),
    breakFrame(false),
    fx('dark-on'),
    n('レニィが、微笑んだ。'),
    n('その微笑みは、諦めた人の微笑みだった。'),
    d('LEN', 'そっかぁ。'),
    d('LEN', 'じゃあ、また、十三日だね。'),
    jump('be07_open'),
  ),
];
